# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['frontend\\app.py'],
    pathex=['.'],  # Add current directory to Python path
    binaries=[],
    datas=[
        ('frontend/bg_image.jpg', 'frontend'), 
        ('frontend/left_logo.jpg', 'frontend'), 
        ('frontend/right_logo.jpg', 'frontend'),
        ('frontend/logo.png', 'frontend'),
        ('frontend/views', 'frontend/views'),
        ('db_connect.py', '.'),
        ('add_account.py', '.'),
        ('add_payment.py', '.'),
        ('add_receipt.py', '.'),
        ('bring_forward.py', '.'),
        ('brought_forward_balances.py', '.'),
        ('depreciate_property.py', '.'),
        ('fd_approve_maturity.py', '.'),
        ('fd_maturity_update.py', '.'),
        ('journal_utils.py', '.'),
        ('list_sundry_credits.py', '.'),
        ('monthly_balance_sheet_simple.py', '.'),
        ('monthly_balance_sheet.py', '.'),
        ('utils.py', '.'),
        ('test_connection.py', '.'),
        ('account_utils.py', '.'),
        ('balance_utils.py', '.'),
        ('ensure_account_types.py', '.'),
        ('transaction_approver.py', '.')
    ],
    hiddenimports=[
        'mysql.connector',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'tkinter',
        'tkinter.ttk',
        'db_connect',
        'add_account',
        'add_payment',
        'add_receipt',
        'bring_forward',
        'brought_forward_balances',
        'depreciate_property',
        'fd_approve_maturity',
        'fd_maturity_update',
        'journal_utils',
        'list_sundry_credits',
        'monthly_balance_sheet_simple',
        'monthly_balance_sheet',
        'utils',
        'test_connection',
        'account_utils',
        'balance_utils',
        'ensure_account_types',
        'transaction_approver'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['pyi_rth_add_path.py'],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='BAHI-KHATA',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Changed to False for windowed app
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='frontend/app_icon.ico',  # Added icon
)
